# Generated by Django 5.1.1 on 2024-09-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_doctors_doc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_on',
            field=models.DateField(),
        ),
    ]
