# Generated by Django 5.1.1 on 2024-09-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_booking_book_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_on',
            field=models.DateField(auto_now=True),
        ),
    ]
